#pragma once

#include "keyManager.h"
#include "ColliderManager.h"
#include "ImageManager.h"
#include "CameraManager.h"
#include "TagManager.h"
#include "TextDataManager.h"
#include "TimeManager.h"
#include "SceneManager.h"
#include "ZOrderManager.h"
#include "soundManager.h"
#include "ClipManager.h"
#include "EffectManager.h"
#include "UIManager.h"
#include "MouseManager.h"